import{a as b,i as L,S}from"./assets/vendor-BGz2EIcA.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const w="https://pixabay.com/api/",q="47085214-4cff0ba1bb96c64321ec3a8d9";async function v(e,t=1){try{return(await b.get(w,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(n){throw console.error("Error fetching images",n),n}}function $(e,t){if(!e||e.length===0){l("No images found!");return}const n=e.map(({webformatURL:c,largeImageURL:r,tags:o,likes:a,views:m,comments:h,downloads:g})=>`
    <a class="gallery-item" href="${r}" data-title="${o}">
      <img src="${c}" alt="${o}" loading="lazy"/>
      <div class="info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${m}</p>
        <p><b>Comments:</b> ${h}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n)}function l(e,t="topRight"){try{L.show({message:e,position:t,timeout:3e3})}catch(n){console.error("Error displaying notification:",n)}}function E(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}let u="",i=1,s=0;const M=document.querySelector(".form"),f=document.querySelector(".gallery"),d=document.querySelector(".load-more"),y=document.querySelector(".loader"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});M.addEventListener("submit",O);d.addEventListener("click",B);function O(e){e.preventDefault(),u=e.currentTarget.elements.query.value.trim(),u&&(A(),p())}function A(){i=1,s=0,f.innerHTML="",d.style.display="none"}function B(){i++,p()}async function p(){N();try{const{hits:e,totalHits:t}=await v(u,i);H(e,t)}catch{l("Failed to load images. Please try again later.")}finally{x()}}function H(e,t){if(i===1&&(s=t,!s)){l("Sorry, there are no images matching your search query. Please try again!");return}$(e,f),P.refresh(),I(e),i>1&&E()}function I(e){const t=e.length===15&&i*15<s;d.style.display=t?"block":"none",!t&&i*15>=s&&l("We're sorry, but you've reached the end of search results.")}function N(){y.style.display="block"}function x(){y.style.display="none"}
//# sourceMappingURL=index.js.map
